### ISSUE TITLE
How to build weasyprint?

### ISSUE THREAD

**Issue by ptzedakis** [CourtBouillon/weasyprint-samples#8]
Hello, 
I just downloaded the weasyprint-samples but I cannot find weasyprint executable or source code to build it and use it with the examples. Am I missing something ?

Thank you,
P.

**Comment by liZe** [comment]
On https://weasyprint.org/ you have a link to the documentation, where you’ll find [the installation guide](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation).

**Comment by ptzedakis** [comment]
Hi,
Thank you! I found it!
BR,
P.

--
Panayotis Tzedakis, PSM I<https://www.scrum.org/user/622884>
Senior Technical Consultant @ NetHabilis<http://www.nethabilis.com/>

Like my work? Please consider endorsing my skills on LinkedIn<https://gr.linkedin.com/in/panayotis>. Thank you!

***@***.***
